name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: '18'
      - name: NPM Install
        run: if [ -e package-lock.json ]; then npm ci; else npm i; fi
      - name: Run eslint linter
        run: npx eslint --max-warnings 0 .
      - name: Run TypeScript compiler
        run: npx tsc
      - name: Run Prettier code style checks
        run: npx prettier -c .
